# Task: Explore in Google and Make a document :

# 1. What are basic checks we do for pandas dataframe?
# 2. What is pandas dataframe?

# Task: Write a program

# Q> create and import below files. print basic check of all files dataframe?
import pandas as pd
# 1. Create a friend_names.csv file delimiter is comma(,)  (atleast 10 names, columns are FriendName,Quality)
df_friend_names=pd.read_csv(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\friends_names.csv")
print(df_friend_names)
print(df_friend_names.columns)
print(df_friend_names.shape)
print(df_friend_names.head())
print(df_friend_names.head(7))
print(df_friend_names.tail())
print(df_friend_names.dtypes)
print(df_friend_names.info())
print(df_friend_names.index)

# 2. Create a family_members.txt file delimiter is star (*), (atleast 10 names, columns are FamilyMemberName*Relation)
df_family_members=pd.read_csv(r"C:\\Users\Abdul\\Downloads\\assignment8.a\\family_memberst.txt")
print(df_family_members)
print(df_family_members.columns)
print(df_family_members.shape)
print(df_family_members.head())
print(df_family_members.head(7))
print(df_family_members.tail())
print(df_family_members.dtypes)
print(df_family_members.info())
print(df_family_members.index)

# 3. Create a Vegfood_items.txt file delimiter is pipe (|), (atleast 10 names, columns are VegFoodName*Taste)
df_Vegfood_items=pd.read_csv(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\Vegfood_items_pipe.txt")
print(df_Vegfood_items)
print(df_Vegfood_items.columns)
print(df_Vegfood_items.shape)
print(df_Vegfood_items.head())
print(df_Vegfood_items.head(7))
print(df_Vegfood_items.tail())
print(df_Vegfood_items.dtypes)
print(df_Vegfood_items.info())
print(df_Vegfood_items.index)

# 4. Create a NonVegfood_items.txt file delimiter is pipe (|), (atleast 10 names, columns are NonVegFoodName*Taste)
df_NonVegfood_items=pd.read_csv(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\Non_Vegfood_items_pipe.txt")
print(df_NonVegfood_items)
print(df_NonVegfood_items.columns)
print(df_NonVegfood_items.shape)
print(df_NonVegfood_items.head())
print(df_NonVegfood_items.head(7))
print(df_NonVegfood_items.tail())
print(df_NonVegfood_items.dtypes)
print(df_NonVegfood_items.info())
print(df_NonVegfood_items.index)

# 5. Create a month_names.txt file delimiter is and (&), (atleast 12 names, columns are MonthName*Season)
df_month_names=pd.read_csv(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\month_names&.txt")
print(df_month_names)
print(df_month_names.columns)
print(df_month_names.shape)
print(df_month_names.head())
print(df_month_names.head(7))
print(df_month_names.tail())
print(df_month_names.dtypes)
print(df_month_names.info())
print(df_month_names.index)

# 6. Create a colours_names.txt file delimiter is cap (^), (atleast 12 names, columns are colourName_in_English^colourName_in_Hindi^colourName_in_Telugu)
df_colour_names=pd.read_csv(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\colours_names^.txt")
print(df_colour_names)
print(df_colour_names.columns)
print(df_colour_names.shape)
print(df_colour_names.head())
print(df_colour_names.head(7))
print(df_colour_names.tail())
print(df_colour_names.dtypes)
print(df_colour_names.info())
print(df_colour_names.index)

# 7. Create a friend_names.xls file  (atleast 10 names, columns are FriendName,Quality)
df_friend_names=pd.read_excel(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\friend_names.xls")
print(df_friend_names)
print(df_friend_names.columns)
print(df_friend_names.shape)
print(df_friend_names.head())
print(df_friend_names.head(7))
print(df_friend_names.tail())
print(df_friend_names.dtypes)
print(df_friend_names.info())
print(df_friend_names.index)

# 8. Create a family_members.xls file  (atleast 10 names, columns are FamilyMemberName*Relation)
df_family_members1=pd.read_excel(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\family_members.xls")
print(df_family_members1)
print(df_family_members1.columns)
print(df_family_members1.shape)
print(df_family_members1.head())
print(df_family_members1.head(7))
print(df_family_members1.tail())
print(df_family_members1.dtypes)
print(df_family_members1.info())
print(df_family_members1.index)

# 9. Create a Vegfood_items.xlsx file  (atleast 10 names, columns are VegFoodName*Taste)
df_Vegfood_items1=pd.read_excel(r"C:\\Users\Abdul\\Downloads\\assignment8.a\\Vegfood_items.xlsx")
print(df_Vegfood_items1)
print(df_Vegfood_items1.columns)
print(df_Vegfood_items1.shape)
print(df_Vegfood_items1.head())
print(df_Vegfood_items1.head(7))
print(df_Vegfood_items1.tail())
print(df_Vegfood_items1.dtypes)
print(df_Vegfood_items1.info())
print(df_Vegfood_items1.index)

# 10. Create a NonVegfood_items.xlsx file  (atleast 10 names, columns are NonVegFoodName*Taste)
df_NonVegfood_items1=pd.read_excel(r"C:\Users\Abdul\Downloads\assignment8.a\NonVegfood_items.xlsx")
print(df_NonVegfood_items1)
print(df_NonVegfood_items1.columns)
print(df_NonVegfood_items1.shape)
print(df_NonVegfood_items1.head())
print(df_NonVegfood_items1.head(7))
print(df_NonVegfood_items1.tail())
print(df_NonVegfood_items1.dtypes)
print(df_NonVegfood_items1.info())
print(df_NonVegfood_items1.index)

# 11. Create a month_names.xlsx file (atleast 12 names, columns are MonthName*Season)
df_month_names1=pd.read_excel(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\month_names.xlsx")
print(df_month_names1)
print(df_month_names1.columns)
print(df_month_names1.shape)
print(df_month_names1.head())
print(df_month_names1.head(7))
print(df_month_names1.tail())
print(df_month_names1.dtypes)
print(df_month_names1.info())
print(df_month_names1.index)

# 12. Create a colours_names.xlsx file  (atleast 12 names, columns are colourName_in_English^colourName_in_Hindi^colourName_in_Telugu)
df_colours_names=pd.read_excel(r"C:\\Users\\Abdul\\Downloads\\assignment8.a\\colours_names.xlsx")
print(df_colours_names)
print(df_colours_names.columns)
print(df_colours_names.shape)
print(df_colours_names.head())
print(df_colours_names.head(7))
print(df_colours_names.tail())
print(df_colours_names.dtypes)
print(df_colours_names.info())
print(df_colours_names.index)


